service: mes-journal-service

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  environment:
    JOURNALS_DDB_TABLE_NAME: journals
    TEST_CENTRE_DDB_TABLE_NAME: testCentres
    DDB_OFFLINE_ENDPOINT: http://localhost:8000
    AWS_ACCESS_KEY_ID: accessKeyId
    AWS_SECRET_ACCESS_KEY: secretAccessKey

package:
  individually: true

functions:
  getJournal:
    handler: src/functions/getJournal/framework/handler.handler
    events:
      - http:
          path: 'journals/{staffNumber}/personal'
          method: get
  searchBooking:
    handler: src/functions/searchBooking/framework/handler.handler
    events:
      - http:
          path: 'journals/{staffNumber}/search'
          method: get
  getTestCentreJournal:
    handler: src/functions/getTestCentreJournal/framework/handler.handler
    events:
      - http:
          path: 'journals/testcentre/{testCentreId?}'
          method: get

custom:
  dynamodb:
    stages:
      - test
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: journals
            sources: [./test-data/dynamo-seed-journal.json]
          - table: testCentres
            sources: [./test-data/dynamo-seed-test-centre-journal.json]
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

resources:
  Resources:
    journals:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.JOURNALS_DDB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: staffNumber
            AttributeType: S
        KeySchema:
          - AttributeName: staffNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    testCentres:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEST_CENTRE_DDB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: staffNumber
            AttributeType: S
        KeySchema:
          - AttributeName: staffNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-dynamodb
  - serverless-offline
