name: Create Release tfvars

on:
  push:
    tags:
      - release-*

permissions:
  id-token: write
  contents: write

jobs:
  create-release-tfvars:
    runs-on: ubuntu-latest

    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v4

      - name: hi
        uses: dvsa/des-workflow-actions/.github/actions/service-release-tfvars@MES-9153-gha-release-tfvars
        with:
          component: 'api'
          secrets: ${{ toJSON(secrets) }}
