name: Create Release tfvars

on:
  push:
    tags:
      - release-*

permissions:
  id-token: write
  contents: write

jobs:
  pre-creation-checks:
    runs-on: ubuntu-latest
    outputs:
      release_build_required: ${{ steps.pre-creation-checks.outputs.release_build_required }}
      branch: ${{ steps.pre-creation-checks.outputs.branch }}
    steps:
      - uses: actions/checkout@v4
      - name: Pre Creation Checks
        id: pre-creation-checks
        uses: dvsa/des-workflow-actions/.github/actions/create-release-tfvars/pre-creation-checks@MES-9153-gha-release-tfvars
        with:
          component: 'api'
          secrets: ${{ toJSON(secrets) }}

  build-artefact-for-release:
    needs: pre-creation-checks
    if: ${{ needs.pre-creation-checks.outputs.release_build_required }}
    uses: dvsa/des-workflow-actions/.github/workflows/deploy-backend.yaml@MES-9153-gha-release-tfvars
    with:
      branch: ${{ needs.pre-creation-checks.outputs.branch }}
      component: 'api'
    secrets: inherit

  create-release-tfvars:
    needs: [pre-creation-checks, build-artefact-for-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release tfvars
        uses: dvsa/des-workflow-actions/.github/actions/create-release-tfvars/create-service-release-tfvars@MES-9153-gha-release-tfvars
        with:
          component: 'api'
          secrets: ${{ toJSON(secrets) }}