name: Create Release Manifest
on:
  push:
    tags:
      - release-*

permissions:
  id-token: write
  contents: write

jobs:
  release-manifest:
    uses: dvsa/des-workflow-actions/.github/workflows/release-manifest.yaml@MES-9153-gha-release-tfvars
    with:
      component: 'api'
    secrets: inherit